### ISSUE TITLE
No berks install resolution

### ISSUE THREAD

**Issue by boxidau** [dearing/ellk#32]
When using platformstack 3.1.5 berks cannot come up with a solution in conjunction with ellk 0.3.4 this seems to be due to the runit pinned dependency.

**Comment by dearing** [comment]
I'm waiting patiently on upstream to fix a bug breaking tests.  Let's give https://github.com/hw-cookbooks/runit/issues/142 another day or two.  With that resolved we can remove the pinning and free up conflicts.

**Comment by boxidau** [comment]
:+1:

**Comment by dearing** [comment]
As a bandaid you may get away with a pinning like:

```
cookbook 'ellk', '~> 0.3'
cookbook 'runit', '= 1.5.18'
```

This is what I had to do for a runit conflict brought in by a stack.  The whole thing is ugly but so is the bug in runit at the moment.  I had no choice.

**Comment by dearing** [comment]
re-opened #22

**Comment by dearing** [comment]
Runit updated to 1.7 and appears to have solved my issue.  The pinning has been released, please update and review -> https://github.com/dearing/ellk/compare/v0.3.4...v0.3.5.
